const data = {
  products: [
    {
      "id":1,
      name: 'Skim milk',
      slug: 'Skim-milk',
      category: 'milks',
      image: '/images/p1.png',
      price: 30,
      CountInStock: 30,
      brand: 'Faif Life',
      description: 'high quality milk',
    },
    { "id":2,
      name: 'Full cream milk',
      slug: 'Full-cream-milk',
      category: 'milks',
      image: '/images/p2.jpg',
      price: 40,
      CountInStock: 15,
      brand: 'juhayna',
      description: 'high quality milk',
    },
    { "id":3,
      name: 'Sugar free milk',
      slug: 'Sugar-free-milk',
      category: 'milks',
      image: '/images/p3.jpg',
      price: 25,
      CountInStock: 10,
      brand: 'alpro',
      description: 'zero sugar milk',
    },
    { "id":3,
      name: 'Sugar free milk',
      slug: 'Sugar-free-milk',
      category: 'milks',
      image: '/images/p4.jpg',
      price: 25,
      CountInStock: 10,
      brand: 'alpro',
      description: 'zero sugar milk',
    },
    { "id":3,
      name: 'Sugar free milk',
      slug: 'Sugar-free-milk',
      category: 'milks',
      image: '/images/p5.png',
      price: 25,
      CountInStock: 10,
      brand: 'alpro',
      description: 'zero sugar milk',
    },
    {"id":4,
      name: 'Sugar free milk',
      slug: 'Sugar-free-milk',
      category: 'milks',
      image: '/images/p6.png',
      price: 25,
      CountInStock: 10,
      brand: 'alpro',
      description: 'zero sugar milk',
    },
  ],
};
export default data;
